name = "scale-insights-documentation-dashboard"
compatibility_date = "2024-08-20"

[env.production]
name = "scale-insights-documentation-dashboard"

[[env.production.route]]
pattern = "scale-insights-documentation-dashboard.pages.dev"

[build]
command = "npm run build:static"
cwd = ""
watch_dir = "."

[build.upload]
format = "directory"
dir = "dist"